name: CI & Deploy (placeholder – no secrets yet)

on:
  pull_request:
    branches: [main]
  push:
    branches: [main]
  workflow_dispatch:
    inputs:
      target:
        description: "Deployment target"
        required: true
        default: "production"
        type: choice
        options: [production]

permissions:
  contents: read
  deployments: write

env:
  NODE_VERSION: 20

jobs:
  pr_build:
    if: github.event_name == 'pull_request'
    runs-on: ubuntu-latest
    name: PR Build
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: npm
      - run: npm ci
      - run: npm run build

  preview_deploy_placeholder:
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    name: Preview Deploy (placeholder)
    steps:
      - run: echo "Preview deploy skipped (no Vercel token configured)."
      - run: echo "Add VERCEL_TOKEN etc. then implement deploy."

  promote_production_placeholder:
    if: github.event_name == 'workflow_dispatch' && inputs.target == 'production'
    runs-on: ubuntu-latest
    name: Production Deploy (placeholder)
    steps:
      - run: echo "Production deploy skipped (no Vercel token configured)."
      - run: echo "Add secrets and deployment steps here."
